### ISSUE TITLE
CSVから自動データ取得するための基盤整備（CSVの置き場所とかそういうのをISCOと相談）

### ISSUE THREAD

**Issue by wanwanland** [Code-for-OKINAWA/covid19#177] opened 2020-04-08 07:20 UTC

**Comment by amouro** [comment] 2020-04-10 13:33
やります

I'm trying to modify the tool first. So you can easily convert the csv into `/data/data.json`

**Comment by amouro** [comment] 2020-04-10 14:12
Please bear with me to discuss this in English. 
Because after working on the covert tool, I have couple things for you to decide in order to format a correct `data.json`.
Feel free to translate my question or discuss in Japanese.

#### The updated date
![image](https://user-images.githubusercontent.com/3444618/78994736-c389c000-7b7b-11ea-93fd-ecb2824212f3.png)
I know you keep change the `lastUpdate` when the data changed. 
In the tool it is by default set to 8:00am of the next day.
Do you want to use the time when you create the `data.json` ?
https://github.com/Code-for-OKINAWA/covid19/blob/9541c28a98d708b6bce13026ff0b8ff1c56b9bb3/data/data.json#L2

#### Raw data file format
The tool uses Xlsx in order to define the data by specify the area in Excel. ex. A2:J100
Would you mind to convert the csv to excel before running the convert script?

Does anyone have the excel file format that Tokyo uses?

#### 検査実施状況
Would you implement #92 to include the "検査実施人数" soon?
The tool has the processor, too.

**Comment by amouro** [comment] 2020-04-10 14:27
Sorry I have so many questions.

I do have one tool that process the file correct.
You can try it in my branch https://github.com/amouro/covid19/tree/feature/%23177-csv-to-data

The following steps shows how does it work.
### Step 1 convert csv to Excel
Open CSV with Excel and save it to `/tool/download/沖縄県患者発生発表数-RAW.xlsx`

### Add a data update time to the file
This is the 更新時間 of the latest ISCO file.
The place is now in Q2, and the date was designed to a special format, in order to avoid rewrite by excel.
`#2020/04/10/ 18:00#`
![image](https://user-images.githubusercontent.com/3444618/78997613-de5f3300-7b81-11ea-8df1-790ab64e0ea7.png)

### A file called 検査実施サマリ.xlsx
For the 検査実施人数 data and I assume you're going to have more data from issue #92 
Please add this file.
[検査実施サマリ.xlsx](https://github.com/Code-for-OKINAWA/covid19/files/4461938/default.xlsx)

### Setup tool ( /tool/README.md)
`$ cd tool/`
`$ composer install`

### Run the script
`$ php convert`
The file `/data/data.json` will be replaced.

**Comment by amouro** [comment] 2020-04-10 14:29
```json
{
    "patients": {
        "date": "2020\/04\/10 19:00",
        "data": [
            {
                "確定日": "2020-02-14T08:00:00.000Z",
                "居住地": "南部保健所管内",
                "年代": "60代",
                "性別": "女性",
                "退院": "入院勧告解除",
                "備考": null,
                "date": "2020-02-14"
            },
            {
                "確定日": "2020-02-19T08:00:00.000Z",
                "居住地": "那覇市",
                "年代": "60代",
                "性別": "男性",
                "退院": "入院勧告解除",
                "備考": null,
                "date": "2020-02-19"
            },
            {
                "確定日": "2020-02-20T08:00:00.000Z",
                "居住地": "豊見城市",
                "年代": "80代",
                "性別": "男性",
                "退院": "入院勧告解除",
                "備考": null,
                "date": "2020-02-20"
            },
            {
                "確定日": "2020-03-23T08:00:00.000Z",
                "居住地": "中部保健所管内",
                "年代": "10代",
                "性別": "女性",
                "退院": "入院勧告解除",
                "備考": "この症例は空港検疫による輸入症例となり、県内発生件数には含まれません",
                "date": "2020-03-23"
            },
            {
                "確定日": "2020-03-23T08:00:00.000Z",
                "居住地": "南部保健所管内",
                "年代": "20代",
                "性別": "男性",
                "退院": "入院",
                "備考": null,
                "date": "2020-03-23"
            },
            {
                "確定日": "2020-03-24T08:00:00.000Z",
                "居住地": "東京都",
                "年代": "40代",
                "性別": "男性",
                "退院": "入院",
                "備考": null,
                "date": "2020-03-24"
            },
            {
                "確定日": "2020-03-26T08:00:00.000Z",
                "居住地": "那覇市",
                "年代": "30代",
                "性別": "男性",
                "退院": "入院",
                "備考": null,
                "date": "2020-03-26"
            },
            {
                "確定日": "2020-03-28T08:00:00.000Z",
                "居住地": "那覇市",
                "年代": "30代",
                "性別": "女性",
                "退院": "入院",
                "備考": null,
                "date": "2020-03-28"
            },
            {
                "確定日": "2020-03-28T08:00:00.000Z",
                "居住地": "那覇市",
                "年代": "20代",
                "性別": "女性",
                "退院": "入院",
                "備考": null,
                "date": "2020-03-28"
            },
            {
                "確定日": "2020-03-30T08:00:00.000Z",
                "居住地": "那覇市",
                "年代": "40代",
                "性別": "男性",
                "退院": "入院",
                "備考": null,
                "date": "2020-03-30"
            },
            {
                "確定日": "2020-04-03T08:00:00.000Z",
                "居住地": "中部保健所管内",
                "年代": "20代",
                "性別": "男性",
                "退院": "入院",
                "備考": null,
                "date": "2020-04-03"
            },
            {
                "確定日": "2020-04-03T08:00:00.000Z",
                "居住地": "東京都",
                "年代": "30代",
                "性別": "男性",
                "退院": "入院",
                "備考": null,
                "date": "2020-04-03"
            },
            {
                "確定日": "2020-04-04T08:00:00.000Z",
                "居住地": "那覇市",
                "年代": "70代",
                "性別": "男性",
                "退院": "入院",
                "備考": null,
                "date": "2020-04-04"
            },
            {
                "確定日": "2020-04-04T08:00:00.000Z",
                "居住地": "那覇市",
                "年代": "50代",
                "性別": "男性",
                "退院": "入院",
                "備考": null,
                "date": "2020-04-04"
            },
            {
                "確定日": "2020-04-04T08:00:00.000Z",
                "居住地": "南部保健所管内",
                "年代": "20代",
                "性別": "女性",
                "退院": "入院",
                "備考": null,
                "date": "2020-04-04"
            },
            {
                "確定日": "2020-04-04T08:00:00.000Z",
                "居住地": "宜野湾市",
                "年代": "40代",
                "性別": "女性",
                "退院": "入院",
                "備考": null,
                "date": "2020-04-04"
            },
            {
                "確定日": "2020-04-04T08:00:00.000Z",
                "居住地": "中部保健所管内",
                "年代": "30代",
                "性別": "女性",
                "退院": "入院",
                "備考": null,
                "date": "2020-04-04"
            },
            {
                "確定日": "2020-04-06T08:00:00.000Z",
                "居住地": "南部保健所管内",
                "年代": "20代",
                "性別": "男性",
                "退院": "入院",
                "備考": null,
                "date": "2020-04-06"
            },
            {
                "確定日": "2020-04-06T08:00:00.000Z",
                "居住地": "南部保健所管内",
                "年代": "20代",
                "性別": "男性",
                "退院": "入院",
                "備考": null,
                "date": "2020-04-06"
            },
            {
                "確定日": "2020-04-06T08:00:00.000Z",
                "居住地": "那覇市",
                "年代": "20代",
                "性別": "男性",
                "退院": "入院",
                "備考": null,
                "date": "2020-04-06"
            },
            {
                "確定日": "2020-04-06T08:00:00.000Z",
                "居住地": "那覇市",
                "年代": "50代",
                "性別": "女性",
                "退院": "入院",
                "備考": null,
                "date": "2020-04-06"
            },
            {
                "確定日": "2020-04-06T08:00:00.000Z",
                "居住地": "浦添市",
                "年代": "70代",
                "性別": "女性",
                "退院": "入院",
                "備考": null,
                "date": "2020-04-06"
            },
            {
                "確定日": "2020-04-06T08:00:00.000Z",
                "居住地": "那覇市",
                "年代": "50代",
                "性別": "男性",
                "退院": "入院",
                "備考": null,
                "date": "2020-04-06"
            },
            {
                "確定日": "2020-04-07T08:00:00.000Z",
                "居住地": "中部保健所管内",
                "年代": "70代",
                "性別": "男性",
                "退院": "入院",
                "備考": null,
                "date": "2020-04-07"
            },
            {
                "確定日": "2020-04-07T08:00:00.000Z",
                "居住地": "宜野湾市",
                "年代": "80代",
                "性別": "女性",
                "退院": "入院",
                "備考": null,
                "date": "2020-04-07"
            },
            {
                "確定日": "2020-04-07T08:00:00.000Z",
                "居住地": "那覇市",
                "年代": "20代",
                "性別": "女性",
                "退院": "入院",
                "備考": null,
                "date": "2020-04-07"
            },
            {
                "確定日": "2020-04-07T08:00:00.000Z",
                "居住地": "那覇市",
                "年代": "40代",
                "性別": "女性",
                "退院": "入院",
                "備考": null,
                "date": "2020-04-07"
            },
            {
                "確定日": "2020-04-07T08:00:00.000Z",
                "居住地": "浦添市",
                "年代": "50代",
                "性別": "女性",
                "退院": "入院",
                "備考": null,
                "date": "2020-04-07"
            },
            {
                "確定日": "2020-04-07T08:00:00.000Z",
                "居住地": "南城市",
                "年代": "50代",
                "性別": "男性",
                "退院": "入院",
                "備考": null,
                "date": "2020-04-07"
            },
            {
                "確定日": "2020-04-07T08:00:00.000Z",
                "居住地": "南部保健所管内",
                "年代": "50代",
                "性別": "女性",
                "退院": "入院",
                "備考": null,
                "date": "2020-04-07"
            },
            {
                "確定日": "2020-04-07T08:00:00.000Z",
                "居住地": "那覇市",
                "年代": "40代",
                "性別": "女性",
                "退院": "入院",
                "備考": null,
                "date": "2020-04-07"
            },
            {
                "確定日": "2020-04-07T08:00:00.000Z",
                "居住地": "宜野湾市",
                "年代": "40代",
                "性別": "男性",
                "退院": "入院",
                "備考": null,
                "date": "2020-04-07"
            },
            {
                "確定日": "2020-04-07T08:00:00.000Z",
                "居住地": "東京都",
                "年代": "30代",
                "性別": "男性",
                "退院": "入院",
                "備考": null,
                "date": "2020-04-07"
            },
            {
                "確定日": "2020-04-07T08:00:00.000Z",
                "居住地": "那覇市",
                "年代": "40代",
                "性別": "女性",
                "退院": "入院",
                "備考": null,
                "date": "2020-04-07"
            },
            {
                "確定日": "2020-04-07T08:00:00.000Z",
                "居住地": "那覇市",
                "年代": "50代",
                "性別": "男性",
                "退院": "入院",
                "備考": null,
                "date": "2020-04-07"
            },
            {
                "確定日": "2020-04-08T08:00:00.000Z",
                "居住地": "那覇市",
                "年代": "30代",
                "性別": "女性",
                "退院": "入院",
                "備考": null,
                "date": "2020-04-08"
            },
            {
                "確定日": "2020-04-08T08:00:00.000Z",
                "居住地": "豊見城市",
                "年代": "50代",
                "性別": "女性",
                "退院": "入院",
                "備考": null,
                "date": "2020-04-08"
            },
            {
                "確定日": "2020-04-08T08:00:00.000Z",
                "居住地": "沖縄市",
                "年代": "30代",
                "性別": "男性",
                "退院": "入院",
                "備考": null,
                "date": "2020-04-08"
            },
            {
                "確定日": "2020-04-08T08:00:00.000Z",
                "居住地": "沖縄市",
                "年代": "50代",
                "性別": "男性",
                "退院": "入院",
                "備考": null,
                "date": "2020-04-08"
            },
            {
                "確定日": "2020-04-08T08:00:00.000Z",
                "居住地": "中部保健所管内",
                "年代": "20代",
                "性別": "男性",
                "退院": "入院",
                "備考": null,
                "date": "2020-04-08"
            },
            {
                "確定日": "2020-04-09T08:00:00.000Z",
                "居住地": "那覇市",
                "年代": "70代",
                "性別": "女性",
                "退院": "入院調整中",
                "備考": null,
                "date": "2020-04-09"
            },
            {
                "確定日": "2020-04-09T08:00:00.000Z",
                "居住地": "南部保健所管内",
                "年代": "20代",
                "性別": "男性",
                "退院": "入院調整中",
                "備考": null,
                "date": "2020-04-09"
            },
            {
                "確定日": "2020-04-09T08:00:00.000Z",
                "居住地": "浦添市",
                "年代": "20代",
                "性別": "男性",
                "退院": "入院調整中",
                "備考": null,
                "date": "2020-04-09"
            },
            {
                "確定日": "2020-04-10T08:00:00.000Z",
                "居住地": "那覇市",
                "年代": "70代",
                "性別": "女性",
                "退院": "入院調整中",
                "備考": null,
                "date": "2020-04-10"
            },
            {
                "確定日": "2020-04-10T08:00:00.000Z",
                "居住地": "那覇市",
                "年代": "60代",
                "性別": "女性",
                "退院": "入院調整中",
                "備考": null,
                "date": "2020-04-10"
            },
            {
                "確定日": "2020-04-10T08:00:00.000Z",
                "居住地": "中部保健所管内",
                "年代": "40代",
                "性別": "男性",
                "退院": "入院調整中",
                "備考": null,
                "date": "2020-04-10"
            },
            {
                "確定日": "2020-04-10T08:00:00.000Z",
                "居住地": "中部保健所管内",
                "年代": "70代",
                "性別": "女性",
                "退院": "入院",
                "備考": null,
                "date": "2020-04-10"
            },
            {
                "確定日": "2020-04-10T08:00:00.000Z",
                "居住地": "中部保健所管内",
                "年代": "60代",
                "性別": "男性",
                "退院": "入院調整中",
                "備考": null,
                "date": "2020-04-10"
            },
            {
                "確定日": "2020-04-10T08:00:00.000Z",
                "居住地": "那覇市",
                "年代": "40代",
                "性別": "男性",
                "退院": "入院",
                "備考": null,
                "date": "2020-04-10"
            },
            {
                "確定日": "2020-04-10T08:00:00.000Z",
                "居住地": "那覇市",
                "年代": "50代",
                "性別": "男性",
                "退院": "入院",
                "備考": null,
                "date": "2020-04-10"
            }
        ]
    },
    "patients_summary": {
        "date": "2020\/04\/10 19:00",
        "data": [
            {
                "日付": "2020-02-14T08:00:00.000Z",
                "小計": 1
            },
            {
                "日付": "2020-02-15T08:00:00.000Z",
                "小計": 0
            },
            {
                "日付": "2020-02-16T08:00:00.000Z",
                "小計": 0
            },
            {
                "日付": "2020-02-17T08:00:00.000Z",
                "小計": 0
            },
            {
                "日付": "2020-02-18T08:00:00.000Z",
                "小計": 0
            },
            {
                "日付": "2020-02-19T08:00:00.000Z",
                "小計": 1
            },
            {
                "日付": "2020-02-20T08:00:00.000Z",
                "小計": 1
            },
            {
                "日付": "2020-02-21T08:00:00.000Z",
                "小計": 0
            },
            {
                "日付": "2020-02-22T08:00:00.000Z",
                "小計": 0
            },
            {
                "日付": "2020-02-23T08:00:00.000Z",
                "小計": 0
            },
            {
                "日付": "2020-02-24T08:00:00.000Z",
                "小計": 0
            },
            {
                "日付": "2020-02-25T08:00:00.000Z",
                "小計": 0
            },
            {
                "日付": "2020-02-26T08:00:00.000Z",
                "小計": 0
            },
            {
                "日付": "2020-02-27T08:00:00.000Z",
                "小計": 0
            },
            {
                "日付": "2020-02-28T08:00:00.000Z",
                "小計": 0
            },
            {
                "日付": "2020-02-29T08:00:00.000Z",
                "小計": 0
            },
            {
                "日付": "2020-03-01T08:00:00.000Z",
                "小計": 0
            },
            {
                "日付": "2020-03-02T08:00:00.000Z",
                "小計": 0
            },
            {
                "日付": "2020-03-03T08:00:00.000Z",
                "小計": 0
            },
            {
                "日付": "2020-03-04T08:00:00.000Z",
                "小計": 0
            },
            {
                "日付": "2020-03-05T08:00:00.000Z",
                "小計": 0
            },
            {
                "日付": "2020-03-06T08:00:00.000Z",
                "小計": 0
            },
            {
                "日付": "2020-03-07T08:00:00.000Z",
                "小計": 0
            },
            {
                "日付": "2020-03-08T08:00:00.000Z",
                "小計": 0
            },
            {
                "日付": "2020-03-09T08:00:00.000Z",
                "小計": 0
            },
            {
                "日付": "2020-03-10T08:00:00.000Z",
                "小計": 0
            },
            {
                "日付": "2020-03-11T08:00:00.000Z",
                "小計": 0
            },
            {
                "日付": "2020-03-12T08:00:00.000Z",
                "小計": 0
            },
            {
                "日付": "2020-03-13T08:00:00.000Z",
                "小計": 0
            },
            {
                "日付": "2020-03-14T08:00:00.000Z",
                "小計": 0
            },
            {
                "日付": "2020-03-15T08:00:00.000Z",
                "小計": 0
            },
            {
                "日付": "2020-03-16T08:00:00.000Z",
                "小計": 0
            },
            {
                "日付": "2020-03-17T08:00:00.000Z",
                "小計": 0
            },
            {
                "日付": "2020-03-18T08:00:00.000Z",
                "小計": 0
            },
            {
                "日付": "2020-03-19T08:00:00.000Z",
                "小計": 0
            },
            {
                "日付": "2020-03-20T08:00:00.000Z",
                "小計": 0
            },
            {
                "日付": "2020-03-21T08:00:00.000Z",
                "小計": 0
            },
            {
                "日付": "2020-03-22T08:00:00.000Z",
                "小計": 0
            },
            {
                "日付": "2020-03-23T08:00:00.000Z",
                "小計": 2
            },
            {
                "日付": "2020-03-24T08:00:00.000Z",
                "小計": 1
            },
            {
                "日付": "2020-03-25T08:00:00.000Z",
                "小計": 0
            },
            {
                "日付": "2020-03-26T08:00:00.000Z",
                "小計": 1
            },
            {
                "日付": "2020-03-27T08:00:00.000Z",
                "小計": 0
            },
            {
                "日付": "2020-03-28T08:00:00.000Z",
                "小計": 2
            },
            {
                "日付": "2020-03-29T08:00:00.000Z",
                "小計": 0
            },
            {
                "日付": "2020-03-30T08:00:00.000Z",
                "小計": 1
            },
            {
                "日付": "2020-03-31T08:00:00.000Z",
                "小計": 0
            },
            {
                "日付": "2020-04-01T08:00:00.000Z",
                "小計": 0
            },
            {
                "日付": "2020-04-02T08:00:00.000Z",
                "小計": 0
            },
            {
                "日付": "2020-04-03T08:00:00.000Z",
                "小計": 2
            },
            {
                "日付": "2020-04-04T08:00:00.000Z",
                "小計": 5
            },
            {
                "日付": "2020-04-05T08:00:00.000Z",
                "小計": 0
            },
            {
                "日付": "2020-04-06T08:00:00.000Z",
                "小計": 6
            },
            {
                "日付": "2020-04-07T08:00:00.000Z",
                "小計": 12
            },
            {
                "日付": "2020-04-08T08:00:00.000Z",
                "小計": 5
            },
            {
                "日付": "2020-04-09T08:00:00.000Z",
                "小計": 3
            },
            {
                "日付": "2020-04-10T08:00:00.000Z",
                "小計": 7
            }
        ]
    },
    "lastUpdate": "2020\/04\/10 22:59",
    "main_summary": {
        "attr": "検査実施人数",
        "value": 333,
        "children": [
            {
                "attr": "陽性患者数（県外感染者含む）",
                "value": 50,
                "children": [
                    {
                        "attr": "入院中（調整中含む）",
                        "value": 46,
                        "children": [
                            {
                                "attr": "軽症・中等症",
                                "value": 49
                            },
                            {
                                "attr": "重症",
                                "value": 0
                            }
                        ]
                    },
                    {
                        "attr": "退院",
                        "value": 4
                    },
                    {
                        "attr": "死亡",
                        "value": 0
                    }
                ]
            }
        ]
    }
}
```

**Comment by amouro** [comment] 2020-04-10 14:32
A sample of the `data.json` created by the converter

```json
{
    "patients": {
        "date": "2020\/04\/10 19:00",
        "data": [
            {
                "確定日": "2020-02-14T08:00:00.000Z",
                "居住地": "南部保健所管内",
                "年代": "60代",
                "性別": "女性",
                "退院": "入院勧告解除",
                "備考": null,
                "date": "2020-02-14"
            },
            {
                "...": "...."
            },
            {
                "確定日": "2020-04-10T08:00:00.000Z",
                "居住地": "那覇市",
                "年代": "40代",
                "性別": "男性",
                "退院": "入院",
                "備考": null,
                "date": "2020-04-10"
            },
            {
                "確定日": "2020-04-10T08:00:00.000Z",
                "居住地": "那覇市",
                "年代": "50代",
                "性別": "男性",
                "退院": "入院",
                "備考": null,
                "date": "2020-04-10"
            }
        ]
    },
    "patients_summary": {
        "date": "2020\/04\/10 19:00",
        "data": [
            {
                "日付": "2020-02-14T08:00:00.000Z",
                "小計": 1
            },
            {
                "日付": "2020-02-15T08:00:00.000Z",
                "小計": 0
            },
            {
                "...": "...."
            },
            {
                "日付": "2020-04-10T08:00:00.000Z",
                "小計": 7
            }
        ]
    },
    "lastUpdate": "2020\/04\/10 22:59",
    "main_summary": {
        "attr": "検査実施人数",
        "value": 333,
        "children": [
            {
                "attr": "陽性患者数（県外感染者含む）",
                "value": 50,
                "children": [
                    {
                        "attr": "入院中（調整中含む）",
                        "value": 46,
                        "children": [
                            {
                                "attr": "軽症・中等症",
                                "value": 49
                            },
                            {
                                "attr": "重症",
                                "value": 0
                            }
                        ]
                    },
                    {
                        "attr": "退院",
                        "value": 4
                    },
                    {
                        "attr": "死亡",
                        "value": 0
                    }
                ]
            }
        ]
    }
}
```

**Comment by amouro** [comment] 2020-04-11 09:57
Make the convert tool available for CSV file.

**Comment by amouro** [comment] 2020-04-12 07:34
#248 プルリクレビューお願いします

## Feature and Changes
- update converter for Okinawa data
- Adapt both xlsx and csv file format
- Add github action to convert the file after push to development

## HOW-TO
1. Update file `tool/downloads/cases.csv` and `tool/downloads/summary.csv`
  - **cases.csv** - The CSV file provided by ISCO.
  - **summary.csv** - The last data update time and 検査実施人数
2. Commit to development
3. **DONE**
  - GitHub action will run Data Builder and convert data.json
  - GitHub action will commit the data.json

## PS
- The branch already has the latest cases.csv from 11th Apr. 
- PR has conflict on data.json to be merged.

**Comment by amouro** [comment] 2020-04-12 08:53
@mami-miyagi I'm not sure if you want to close this issue now before we can get CSV file from ISCO server.

**Comment by amouro** [comment] 2020-04-13 09:43
CSVから自動データ取得URL: 
https://isc-okinawa.org/opendata/470007_okinawa_covid19_patients.csv

**Comment by amouro** [comment] 2020-04-14 04:19
@m3n3m https://github.com/Code-for-OKINAWA/covid19/commit/5171010f5ef95496c5e4de3ff9db0d78f1882ef4

患者_退院済フラグ データないのは入院調整中ですか? 確認お願いします。

**Comment by m3n3m** [comment] 2020-04-14 04:22
@amouro 患者_退院済フラグ データないところは「入院調整中」です。

**Comment by amouro** [comment] 2020-04-14 09:04
@m3n3m I've submit a PR to match the rule. #283

**Comment by amouro** [comment] 2020-04-14 09:36
In #283 PR
I make the Github Action download the [CSV](https://isc-okinawa.org/opendata/470007_okinawa_covid19_patients.csv)

## HOW-TO Update ( after merged )
### When?
When Ayane Ish notify us that ISCO has update the CSV**
### Steps
- Update the `summary.csv` in `更新時間` field
- Commit to `development` branch
- **DONE** (Data Builder will start)

### WHAT converter do?
1. **Download** the csv
1. **Convert** to JSON
1. **Commit** the update `cases.csv` and `data.json`

**Comment by amouro** [comment] 2020-04-15 14:01
## Update
- Only trigger the data builder when `summary.csv` changed
- Map empty field of "居住地", "年代", "性別" to "調査中"
![Screen Shot on 2020-04-15 at 22:51:56](https://user-images.githubusercontent.com/3444618/79345994-c9f9ac80-7f6c-11ea-9fb0-c0cb4edf6959.png)

**Comment by amouro** [comment] 2020-04-16 13:32
## Update data builder for the latest CSV change.

### Discharge status
```
    0: "入院",
    1: "退院",
    2: "入院調整中"
    NULL: "確認中"
```
### 居住地・年代・性別
```
NULL: 調査中
```
![image](https://user-images.githubusercontent.com/3444618/79462105-0c38f180-8032-11ea-88c7-6606a18b3ef1.png)

### Result sample
![Screen Shot on 2020-04-16 at 22:29:01](https://user-images.githubusercontent.com/3444618/79461860-b2d0c280-8031-11ea-9b95-90b715cde941.png)

**Comment by amouro** [comment] 2020-04-16 13:39
### 追加患者状態
Map column `患者_状態` into data.json.

![image](https://user-images.githubusercontent.com/3444618/79462804-f546cf00-8032-11ea-98a6-f27221f14dc8.png)

> Reference "患者の状態を次のいずれかの文字列で記載。（不明やその他公開できない場合は空欄とする）
{無症状, 軽症, 中等症, 重症, 死亡}"

**Comment by amouro** [comment] 2020-04-17 08:13
レビューお願いします

I would like to merge the current feature to development if the converter is good.

And let's discuss if we want to schedule it and run it automatically in specific time.

**Comment by amouro** [comment] 2020-04-19 06:19
Converter deployed. @masakifujie please consider close this issue. Thanks

**Closed** 2020-04-23 04:14 UTC
Labels: 優先度：高
